services:
  api:
    build: ./services/api
    container_name: koconi_api
    ports:
      - "3000:3000"
    env_file:
      - ./services/api/.env
    depends_on:
      - koconi_db
    restart: unless-stopped

  lp:
    build: ./apps/LP
    container_name: koconi_lp
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  koconi_db:
    image: postgres:16-alpine
    container_name: koconi_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=koconi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    ports:
      - "80:80"
    build: ./infra/nginx
    container_name: koconi_nginx
    volumes:
      - ./apps/LP/dist:/usr/share/nginx/html:ro
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - lp
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: koconi_cloudflared
    command: tunnel --no-autoupdate --protocol http2 run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx
    restart: unless-stopped

  ai:
    build: ./services/ai
    container_name: koconi_ai
    ports:
      - "8000:8000"
    volumes:
      - ./services/ai:/app
    restart: unless-stopped

volumes:
  postgres_data: