/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            memories: components["schemas"]["Memory"][];
                        };
                    };
                };
                500: components["responses"]["Error500"];
            };
        };
        put?: never;
        /** Create memory */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMemoryRequest"];
                };
            };
            responses: {
                /** @description Memory created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            memory: components["schemas"]["Memory"];
                        };
                    };
                };
                400: components["responses"]["Error400"];
                500: components["responses"]["Error500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create photo metadata */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePhotoRequest"];
                };
            };
            responses: {
                /** @description Photo created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            photo: components["schemas"]["Photo"];
                        };
                    };
                };
                400: components["responses"]["Error400"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/photos/{photoID}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match uploaded image to landmark assets */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoID: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["MatchPhotoRequest"];
                };
            };
            responses: {
                /** @description Match result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            result: components["schemas"]["AIMatchResult"];
                        };
                    };
                };
                400: components["responses"]["Error400"];
                404: components["responses"]["Error404"];
                500: components["responses"]["Error500"];
                502: components["responses"]["Error502"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List placements by map bounds */
        get: {
            parameters: {
                query: {
                    min_lat: number;
                    max_lat: number;
                    min_lng: number;
                    max_lng: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Placements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            placements: components["schemas"]["LandmarkPlacement"][];
                        };
                    };
                };
                400: components["responses"]["Error400"];
            };
        };
        put?: never;
        /** Create landmark placement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePlacementRequest"];
                };
            };
            responses: {
                /** @description Placement created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            placement: components["schemas"]["LandmarkPlacement"];
                        };
                    };
                };
                400: components["responses"]["Error400"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateMemoryRequest: {
            title: string;
            description?: string | null;
        };
        Memory: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreatePhotoRequest: {
            device_id: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /**
             * Format: date-time
             * @description RFC3339
             */
            captured_at: string;
            image_key: string;
        };
        Photo: {
            /** Format: int64 */
            id: number;
            device_id: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** Format: date-time */
            captured_at: string;
            image_key: string;
            /** Format: date-time */
            created_at: string;
        };
        MatchPhotoRequest: {
            /** Format: binary */
            file: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            /** @default 5 */
            k: number;
        };
        AICandidate: {
            asset_id: string;
            /** Format: double */
            match_score: number;
            /** Format: double */
            suggested_scale: number;
            suggested_rotation: number[];
        };
        AIMatchResult: {
            candidates: components["schemas"]["AICandidate"][];
        };
        CreatePlacementRequest: {
            /** Format: int64 */
            photo_id: number;
            asset_id: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** Format: double */
            scale: number;
            rotation: number[];
            /** Format: double */
            match_score?: number | null;
        };
        LandmarkPlacement: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            photo_id: number;
            asset_id: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** Format: double */
            scale: number;
            rotation: number[];
            /** Format: double */
            match_score?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        ErrorResponse: {
            /** @example false */
            OK: boolean;
            Error: string;
        };
    };
    responses: {
        /** @description Bad Request */
        Error400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Upstream Error */
        Error502: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal Server Error */
        Error500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
